const SIGN_UP_INIT = 'SIGN_UP_INIT';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_OUT_INIT = 'SIGN_OUT_INIT';
const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export {
  SIGN_UP_INIT,
  SIGN_UP_FAILURE,
  SIGN_UP_SUCCESS,
  SIGN_OUT_INIT,
  SIGN_OUT_FAILURE,
  SIGN_OUT_SUCCESS,
};
