const SIGN_UP_INIT = 'SIGN_UP_INIT';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_OUT_INIT = 'SIGN_OUT_INIT';
const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_IN_INIT = 'SIGN_IN_INIT';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const AUTH_IS_READY = 'AUTH_IS_READY';
const GET_PRODUCTS_INIT = 'GET_PRODUCTS_INIT';
const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export {
  SIGN_UP_INIT,
  SIGN_UP_FAILURE,
  SIGN_UP_SUCCESS,
  SIGN_OUT_INIT,
  SIGN_OUT_FAILURE,
  SIGN_OUT_SUCCESS,
  SIGN_IN_INIT,
  SIGN_IN_FAILURE,
  SIGN_IN_SUCCESS,
  AUTH_IS_READY,
  GET_PRODUCTS_INIT,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCTS_SUCCESS,
};
