// --------AUTHENTICATION
const SIGN_UP_INIT = 'SIGN_UP_INIT';
const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_OUT_INIT = 'SIGN_OUT_INIT';
const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';
const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
const SIGN_IN_INIT = 'SIGN_IN_INIT';
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const AUTH_IS_READY = 'AUTH_IS_READY';
// -----------PRODUCTS
const GET_PRODUCTS_INIT = 'GET_PRODUCTS_INIT';
const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCT_INIT = 'GET_PRODUCT_INIT';
const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
// -----------CART
const GET_CART_INIT = 'GET_CART_INIT';
const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
const GET_CART_FAILURE = 'GET_CART_FAILURE';
const ADD_ITEM_TO_CART_INIT = 'ADD_ITEM_TO_CART_INIT';
const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
const ADD_ITEM_TO_CART_FAILURE = 'ADD_ITEM_TO_CART_FAILURE';
const REMOVE_CART_ITEM_INIT = 'REMOVE_CART_ITEM_INIT';
const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
const REMOVE_CART_ITEM_FAILURE = 'REMOVE_CART_ITEM_FAILURE';
const INCREASE_ITEM_QNT_INIT = 'INCREASE_ITEM_QNT_INIT';
const INCREASE_ITEM_QNT_SUCCES = 'INCREASE_ITEM_QNT_SUCCES';
const INCREASE_ITEM_QNT_FAILURE = 'INCREASE_ITEM_QNT_FAILURE';
const DECREASE_ITEM_QNT_INIT = 'DECREASE_ITEM_QNT_INIT';
const DECREASE_ITEM_QNT_SUCCES = 'DECREASE_ITEM_QNT_SUCCES';
const DECREASE_ITEM_QNT_FAILURE = 'DECREASE_ITEM_QNT_FAILURE';

export {
  SIGN_UP_INIT,
  SIGN_UP_FAILURE,
  SIGN_UP_SUCCESS,
  SIGN_OUT_INIT,
  SIGN_OUT_FAILURE,
  SIGN_OUT_SUCCESS,
  SIGN_IN_INIT,
  SIGN_IN_FAILURE,
  SIGN_IN_SUCCESS,
  AUTH_IS_READY,
  GET_PRODUCTS_INIT,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCT_INIT,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT_FAILURE,
  GET_CART_INIT,
  GET_CART_SUCCESS,
  GET_CART_FAILURE,
  ADD_ITEM_TO_CART_INIT,
  ADD_ITEM_TO_CART_SUCCESS,
  ADD_ITEM_TO_CART_FAILURE,
  REMOVE_CART_ITEM_INIT,
  REMOVE_CART_ITEM_SUCCESS,
  REMOVE_CART_ITEM_FAILURE,
  INCREASE_ITEM_QNT_INIT,
  INCREASE_ITEM_QNT_SUCCES,
  INCREASE_ITEM_QNT_FAILURE,
  DECREASE_ITEM_QNT_INIT,
  DECREASE_ITEM_QNT_SUCCES,
  DECREASE_ITEM_QNT_FAILURE,
};
